### ISSUE TITLE
o modelo não calcula corretamente as datas de simulação em simulação de mútltiplos anos

### ISSUE THREAD

**Issue by camilacbecker** [RomuloPBenedetti/CropModelsUFSM#12]
Se o primeiro ano da simulação é bissexto ele usa o dia do ano de plantio referente a este ano para fazer a simulação para todos os anos e vice-versa.

Por exemplo: Em uma simulação colocamos 55 anos de dados meteorológicos e usamos a data de plantio 04/08. Sendo o primeiro ano da simulação, um ano bissexto, essa data refere-se ao dia do ano: 217. O modelo usa o dia 217 como data de plantio para todos os anos, porém para os anos que não são bissextos esse dia refere-se a data 05/08.

**Comment by RomuloPBenedetti** [comment]
Corrigido no release release 1.1 (435b0a2) do PhenoGlad.
