### ISSUE TITLE
alerta de danos no arquivo logfile

### ISSUE THREAD

**Issue by camilacbecker** [RomuloPBenedetti/CropModelsUFSM#17]
Quando o terceiro dia de temperatura maior que 34 graus ocorre exatamente no dia do R2 o dano aparece na interface mas não aparece no arquivo logfile.

Uma simulação foi realizada com as seguintes informações:

Plantio: 01/08/1980
Precoce
até ponto de colheita
[32_53 xavier teste.txt](https://github.com/RomuloPBenedetti/CropModelsUFSM/files/464006/32_53.xavier.teste.txt)

Nessa simulação o terceiro dia de temperatura alta ocorre no dia juliano 310 que é o dia do R2, e nesse caso o alerta nao aparece no logfile

**Comment by RomuloPBenedetti** [comment]
corrigido no commit a7e241be9119ed962c9e2e859de42c34b8ba696a.
