### ISSUE TITLE
arquivos results para teste

### ISSUE THREAD

**Issue by camilacbecker** [RomuloPBenedetti/CropModelsUFSM#18]
Arquivos results foram enviados para a pasta compartilhada do google drive para testar o script que deverá colocar numa mesma coluna o Dia Juliano que ocorreu o R2 para cada ano da simulação. Mais colunas deverão ser acrescentadas quanto mais datas de plantio forem simuladas.

**Comment by RomuloPBenedetti** [comment]
Se possível adicione o link para o arquivo no issue, issues não devem ser usados para recados.
