### ISSUE TITLE
Conversor-problema na conversão de dados- dias sendo pulados

### ISSUE THREAD

**Issue by jossana** [RomuloPBenedetti/CropModelsUFSM#20]
Foi encontrado um problema no arquivo de dados já convertido para o municipio de Uruguaiana.
O problema é que o conversor pulou um dia, ou seja, do dia 317 pulou para o 319.

OBS: Os valores correspondentes a esses dias foram convertidos de forma correta.

[converter.txt](https://github.com/RomuloPBenedetti/CropModelsUFSM/files/611840/converter.txt)
[converted.txt](https://github.com/RomuloPBenedetti/CropModelsUFSM/files/611839/converted.txt)
[teste Uruguaiana.xlsx](https://github.com/RomuloPBenedetti/CropModelsUFSM/files/611841/teste.Uruguaiana.xlsx)

**Comment by RomuloPBenedetti** [comment]
Foram encontradas melhores opcoes para a obtencao dos dados do INMET e provavelmente o conversor será portado novamente para uma solucao mais simples, componente dos scripts que automatizam a previsão de safra.
